# Define the AWS provider block with the access credentials and region.
provider "aws" {
  region     = "ap-south-1"               # Specify the AWS region.
  access_key = "********************"     # Provide your AWS access key.
  secret_key = "********************"     # Provide your AWS secret key.
}

# Instantiate a VPC module from a local source.
module "vpc" {
  source = "./vpc/"                       # Path to the VPC module directory.
}

# Instantiate a web server module from a local source and connect it to the VPC.
module "web" {
  source    = "./web/"                    # Path to the web server module directory.
  subnet_id = module.vpc.websubnet_id     # Pass the subnet ID from the VPC module.
  vpc_id    = module.vpc.vpc_id            # Pass the VPC ID from the VPC module.
}

# Instantiate an application server module from a local source and connect it to the VPC.
module "app" {
  source    = "./app/"                    # Path to the application server module directory.
  subnet_id = module.vpc.appsubnet_id     # Pass the subnet ID from the VPC module.
  vpc_id    = module.vpc.vpc_id            # Pass the VPC ID from the VPC module.
}

# Instantiate a database server module from a local source and connect it to the VPC.
module "db" {
  source = "./db/"                        # Path to the database server module directory.
  vpc_id = module.vpc.vpc_id               # Pass the VPC ID from the VPC module.
}

# Create an AWS key pair resource.
resource "aws_key_pair" "tf-key-pair" {
  key_name   = "tf-key-pair"              # Specify the key name.
  public_key = tls_private_key.rsa.public_key_openssh  # Use the public key generated by TLS.
}

# Generate an RSA private key using TLS.
resource "tls_private_key" "rsa" {
  algorithm = "RSA"                       # Specify the encryption algorithm.
  rsa_bits  = 4096                        # Specify the key length.
}

# Write the RSA private key to a local file.
resource "local_file" "tf-key" {
  content  = tls_private_key.rsa.private_key_pem  # Specify the private key content.
  filename = "tf-key-pair"                        # Specify the filename.
}
